### ISSUE TITLE
"Send to chart" bug in scatterplot helper

### ISSUE THREAD

**Issue by tjnelson5** [amyrebecca/zootools-sheets#20]
I copied over the most recent spreadsheet version for testing (currently living here: https://docs.google.com/spreadsheets/d/1xkhHDDrRu3gqJrnhnIPu2L4HHFOHF-g8G_rGjQmKYPI/edit#gid=1930796242). I ran into a problem. I'll try to recreate my steps below:

1) The first thing I did was delete the "charts" and "statistics" sheets (by clicking on the down arrows on the sheet tab and selecting delete.  This appeared to work just fine.

2) I then opened the scatterplot helper, and tried to make a plot of student longitude versus. student latitude.  The preview chart looked fine, and as I made changes and hit "plot" the chart updated as expected.  However, when I tried to send the chart to the sheet, I got an error message stating "Something went wrong: TypeError: (class)@63efbbca is not a function, it is undefined."  This was posted in the sidebar.  Any subsequent attempts to update the plot using the "plot button" resulted in the following error message: "Data column(s) for axis #0 cannot be of type string×"

3) I tried this again in another copy of the spreadsheet where I didn't delete the "charts" and "statistics" sheet and I get the same error when trying to send the chart to the sheet.

**Comment by srallen** [comment]
@tjnelson5 I haven't been able to replicate `Something went wrong: TypeError: (class)@63efbbca is not a function, it is undefined.` however, the other error is due to the state of the sidebar not being reset after sending a chart to the sheet. I've updated the add-on and now the state is reset. You can check it out in the Activity One spreadsheet.

I suspect `Something went wrong: TypeError: (class)@63efbbca is not a function, it is undefined.` may have something to do with an application permission failing with the copy which I'm hoping will be resolved once I package up the add-on

FWIW, I was able to successfully copy and use the sheet with my personal gmail account.

**Comment by srallen** [comment]
Closing because I wasn't able to replicate `Something went wrong: TypeError: (class)@63efbbca is not a function, it is undefined.` and now that the add-on is published, then application permissions shouldn't be an issue. Will reopen if anyone reports this.
