### ISSUE TITLE
Send to Sheet Scatter Plot bug

### ISSUE THREAD

**Issue by trouille** [amyrebecca/zootools-sheets#25]
Note: working in Chrome

1) Using 'Scatter plot helper' - if you make the plot of 'Calculated Distance' vs 'Calculated Distance', the plot looks good in the 'helper', but if you send to sheet, the x-axis loses its values. Not sure what's causing this error. It'd be weird to make this plot and want to save it, but the bug could be indicative of some error we should be aware of.

**Comment by srallen** [comment]
ok, I was able to replicate, but don't consider this high priority to fix at the moment.

**Comment by srallen** [comment]
Apparently this is another example of the differences between the `EmbeddedChartBuilder` in the Sheets Apps Script and the Charts API. With the chart in the sheet, I can only set a range for the chart to use, which is a reference to a range of cells in the spreadsheet. What I think is happening is that since the range is the same when the same variable is selected for x and y, that the sheet is doing exactly what we're telling it to: plot only a single column of values. The `EmbeddedChartBuilder` doesn't have any methods or options for me to specific what is x and what is y. 

What I decided to do is prevent users from being able to plot the same variable against each other and it doesn't really make sense to do so unless it was a part of a lesson. Since I can't get the chart in the sheet to display it, then it can't really be used for educational purposes.
