### ISSUE TITLE
Filter data helper: bug filtering on text input

### ISSUE THREAD

**Issue by tjnelson5** [amyrebecca/zootools-sheets#44]
Evaluation of expressions on text input is case sensitive.  For example, type = elliptical will successfully return all the elliptical galaxies, but type = ELLIPTICAL does not.  Can we add a case insensitive flag to the regex?

**Comment by srallen** [comment]
@tjnelson5 There doesn't appear to be a good way around this. I'm only using a regex for the initial input value to determine if it is an allowed number literal or string literal for the query. It's the query language itself that is case sensitive with string literals: https://developers.google.com/chart/interactive/docs/querylanguage#where

There is a function for `upper()` and `lower()`, to convert strings to all uppercase or all lowercase, but the query itself will still be case sensitive when selecting the data, i.e. even if `'ELLIPTICAL'` is converted to lowercase by `lower('ELLIPTICAL')`, it'll only match `elliptical` and not `Elliptical` or other case variants. I also can't assume what original format in the data is; we would have to add a toggle to add `lower()`, `upper()`, or none at all.

I think we should just add in the instructions that text input is case sensitive. It'll also possibly be a good teaching moment about consistency in data, that using mixed case in text can be problematic? 

I did fix an issue with the fuzzy match when using only one filter. It should have been using `contains` rather than the literal `=` with strings, so now an input like `spir` will match `spiral` in the data.

**Comment by tjnelson5** [comment]
Ok, I think the instructions are a good enough solution.  Definitely something we'll address with students in one of the class activities.  If you are happy with this for now, go ahead and close the ticket.

**Comment by srallen** [comment]
Ok I've updated the instructions.
