### ISSUE TITLE
Scatterplot tool "specified range" not working correctly.

### ISSUE THREAD

**Issue by codydirks** [amyrebecca/zootools-sheets#50]
The "specified range" tool does not seem to be working correctly for the y-axis. When I try to plot entries in a specific RA and DEC region (for example, I did an x-axis of RA between 190 and 210, and a y-axis of DEC between -40 and 40), the resulting plot has the incorrect y-axis limits. I tried flipping the x and y axis and got similar incorrect results.

Additionally, the preview plot that is drawn does not seem to reflect the specified ranges.

**Comment by trouille** [comment]
Agreed that setting the range in the preview piece isn't working correctly. However, students can change the axes within the 'charts' tab itself. See attached image for where this happens. 

<img width="669" alt="screen shot 2016-09-12 at 1 40 23 pm" src="https://cloud.githubusercontent.com/assets/4975655/18447980/8ee0599c-78ee-11e6-9ccb-de68751ec5c2.png">

**Comment by trouille** [comment]
I think we wait till winter true Intro2Astro effort to fix this. For now, we could include instructions to the students (in-class and on the assignments) that points out that we know it's a bug but that they can set axes within the 'charts' tab.

**Comment by srallen** [comment]
@codydirks is this like what you're seeing once sent over to the spreadsheet?

![screen shot 2016-09-15 at 2 21 13 pm](https://cloud.githubusercontent.com/assets/5016731/18564096/c475b04e-7b4f-11e6-850f-2c86ddeeaafc.png)

**Comment by codydirks** [comment]
@srallen Yes that's identical to what I get.

**Comment by srallen** [comment]
Ok, I'll see if there've been any changes to the available APIs from Google and if it'd be a quick fix, but I doubt I'll be able to change anything about this until I have guaranteed time to work on it. In the meantime, the students should be directed to edit the ranges using the edit button on the chart itself once it is inserted into the chart.

**Comment by srallen** [comment]
I've been looking over this today and now I remember some details about it:

The Visualization API gives two kinds of options for setting the min and max for the range:
`hAxis.minValue` and `hAxis.maxValue` as well as `vAxis.minValue` and `vAxis.maxValue`. However, these options have the following caveat (quote from `hAxis.maxValue`, but true for all):

> Moves the max value of the horizontal axis to the specified value; this will be rightward in most charts. Ignored if this is set to a value smaller than the maximum x-value of the data. hAxis.viewWindow.max overrides this property.

In the above example, the actual data range is greater than the min or max value set in the option, so it will be ignored. As noted, it can overridden using `viewWindow.max` or `viewWindow.min`, but this doesn't actually set the range min and max, but rather just changes the view window and causes an odd looking plot:

<img width="593" alt="screen shot 2017-01-09 at 2 55 46 pm" src="https://cloud.githubusercontent.com/assets/5016731/21783298/56a3eab2-d67c-11e6-8255-8bcd1168adb3.png">

Since the Google API ignores min and max values if they are less than what is in the data range, then I might suggest we remove the range option from the scatterplot helper entirely and have that be a manual step taught to the students. I can't fix it unless Google decides to change their API.

**Comment by srallen** [comment]
We've decided to remove the range options since I cannot fix it in the way that users will expect it to function.

**Comment by srallen** [comment]
The range options are removed in the latest version.
