### ISSUE TITLE
any recommendation to make the peer review process easier for instructor and students

### ISSUE THREAD

**Issue by JulieAnnKU** [amyrebecca/zootools-sheets#61]
When the students submit their videos, they then have to peer review 3 other views from the class. Is there a way we can set this up to be easier for instructor and students? We talked about a project builder project at one point, but is there something we could set up on google drive?

**Comment by trouille** [comment]
After conversation w/ Julie/Laura, it appears that we may not need a dev solution for this:

- Since instructors aren't using the peer reviews in the grades they're giving their students, then it's no longer a requirement for each video to receive a peer-review. Instead, the instructions to the students can just be to upload their videos to a Google folder, dropbox, youTube channel, or whatever the instructor uses for homework submission/CMS. The folder will just need to be publicly available so that students can go in and select 3 random videos of their own choosing for which to provide a peer-review. 

- Have students submit their peer reviews using a Google form.
