### ISSUE TITLE
401 Error when trying to use Zoo Tools

### ISSUE THREAD

**Issue by wattst** [amyrebecca/zootools-sheets#68]
Receiving a 401 error when attempting to use Zoo Tools for Sheets.

Here is the error I am receiving:

401. That’s an error.

Error: invalid_client

The OAuth client was not found.

Request Details
client_id=507193999702-vo7sl8fluh8lr6emqs8heq9r7vj3tqam@developer.gserviceaccount.com
redirect_uri=https://script.google.com/oauthcallback
state=ACjPJvGkdGjTw9oUiqEfd7seEJTUNUhhO30FKCLY6NcR7itWLcyJ3ATrm4xnMLlZgri6ogNobrH--JavEBrNJndTol4fpkgIWrO0086GsdXrVYPTEc94JAMn5V51ovGK1vnW89BnVUqCprfj_ssLodETjkwoq01vZE8dw-zAan_IIRuDSu0iYwcVdkjvI5NfvSWnN9QNeBpmXiVBlIroWbmqli-GQqhK2VMKwsKbk7JwuHVJ3uyEKalOFo10ec0iOFnFG-9EsYpOkhEEddqZoCh5K4xn4ASuxPBGN3b-DwmuVb5VLCE
scope=https://www.googleapis.com/auth/script.container.ui https://www.googleapis.com/auth/spreadsheets.currentonly
response_type=code none gsession
access_type=offline
approval_prompt=force
hl=en
login_hint=<username>

**Comment by srallen** [comment]
@wattst Thanks for your report. We are working to get the oauth client id authorized by Google.

**Comment by srallen** [comment]
@wattst  We have an identical copy of Zoo Tools for Google Sheets now available on the Add-on store that can be used: https://chrome.google.com/webstore/detail/zoo-tools-for-google-shee/fahnglbfamicnajdcloniiikdmngihgi?authuser=0

Please install this version. The old version will be unpublished soon because the bug with it is on Google's side and I don't know when it'll be resolved.
